export type Screens =
  | 'addMember'
  | 'addTithe'
  | 'addOffer'
  | 'addExpenseCategory'
  | 'addExpense'
  | 'addWithdrawToTheBankAccount'
  | 'editMembers'
  | 'editTithes'
  | 'editOffers'
  | 'editExpenseCategories'
  | 'editExpenses'
  | 'editWithdrawsToTheBankAccount'
  | 'entriesReport'
  | 'outputReport'
  | 'generalReport';
