import { StyleSheet } from '@react-pdf/renderer';
import * as colors from 'tailwindcss/colors';

export const reportStyles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10.5,
    height: '100%',
    paddingBottom: 45,
    paddingLeft: 45,
    paddingRight: 30,
    paddingTop: 30,
    width: '100%',
  },
  bodyReport: {
    alignItems: 'center',
    display: 'flex',
    borderRadius: 4.5,
    color: colors.zinc[100],
    flexDirection: 'column',
    height: '100%',
    width: '100%',
  },
  headerReport: {
    alignItems: 'center',
    backgroundColor: colors.yellow[300],
    borderTopLeftRadius: 4.5,
    borderTopRightRadius: 4.5,
    display: 'flex',
    height: 40,
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
  },
  logoContent: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadiusTopLeft: 4.5,
    display: 'flex',
    height: 75,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    top: 0,
    width: 75,
    zIndex: 50,
  },
  logo: {
    width: 63.8,
  },
  titleReport: {
    borderRadiusTopLeft: 4.5,
    borderRadiusTopRight: 4.5,
    color: colors.zinc[900],
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '0%',
    fontSize: 22.5,
    fontFamily: 'Helvetica-Bold',
    height: 40,
    marginTop: 4.5,
  },
  subtitleContent: {
    alignItems: 'center',
    backgroundColor: colors.yellow[300],
    color: colors.zinc[900],
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    paddingBottom: 4.5,
    width: '100%',
    zIndex: 1,
  },
  subtitleH2: {
    fontSize: 18,
    fontFamily: 'Helvetica-BoldOblique',
    lineHeight: 1.7,
  },
  subtitleH3: {
    fontSize: 13.5,
    fontFamily: 'Helvetica-BoldOblique',
    lineHeight: 1.5,
  },
  subtitleH5: {
    fontSize: 10.5,
    fontWeight: 'normal',
    lineHeight: 1.2,
  },
  reportDate: {
    borderRadius: 4.5,
    color: colors.zinc[900],
    fontSize: 12,
    fontFamily: 'Helvetica-Oblique',
    lineHeight: 1.5,
    padding: 5,
    textAlign: 'right',
    width: '100%',
  },
  mainContent: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    width: '100%',
  },
  info: {
    color: colors.zinc[900],
    display: 'flex',
    flexDirection: 'column',
    fontSize: 9,
    gap: 6,
    padding: 3,
    width: '100%',
  },
  infoContent: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  infoAmount: {
    fontFamily: 'Helvetica-Bold',
    width: '60%',
  },
  table: {
    fontSize: 9,
    width: '100%',
  },
  tableTitle: {
    backgroundColor: colors.blue[600],
    color: colors.zinc[100],
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    padding: 3,
    textAlign: 'center',
    width: '100%',
  },
  tableHeader: {
    alignItems: 'center',
    backgroundColor: colors.zinc[900],
    color: colors.zinc[100],
    display: 'flex',
    flexDirection: 'row',
    fontFamily: 'Helvetica-Bold',
    justifyContent: 'center',
    width: '100%',
  },
  rowLeft: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    padding: 3,
    width: '50%',
  },
  rowRight: {
    display: 'flex',
    borderLeftColor: colors.zinc[300],
    borderLeftStyle: 'solid',
    borderLeftWidth: 1,
    flexDirection: 'row',
    fontFamily: 'Helvetica-Bold',
    justifyContent: 'flex-end',
    padding: 3,
    width: '50%',
  },
  tableRowContent: {
    alignItems: 'center',
    color: colors.zinc[900],
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  subTotalContent: {
    display: 'flex',
    flexDirection: 'row',
    fontFamily: 'Helvetica-Bold',
    justifyContent: 'flex-end',
    width: '100%',
  },
  subTotal: {
    alignItems: 'center',
    backgroundColor: '#F14F1B',
    color: colors.zinc[100],
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 3,
    width: '50%',
  },
  totalContent: {
    alignItems: 'center',
    backgroundColor: colors.yellow[300],
    borderBottomLeftRadius: 4.5,
    borderBottomRightRadius: 4.5,
    color: colors.zinc[900],
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'Helvetica-Bold',
    justifyContent: 'center',
    marginTop: 30,
    padding: 3,
    width: '100%',
  },
  signature: {
    alignItems: 'flex-end',
    color: colors.zinc[900],
    display: 'flex',
    flexDirection: 'row',
    fontSize: 9,
    justifyContent: 'space-evenly',
    gap: 22.5,
    marginTop: 75,
    width: '100%',
  },
  signatureContent: {
    alignItems: 'center',
    color: colors.zinc[900],
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    paddingTop: 7.5,
  },
});
